### ISSUE TITLE
fatal error vec.h :no such file or directory

### ISSUE THREAD

**Issue by bimarsh123** [avun1t/Raytracer#2]
I am having an issue with .h file on the directory despite all the . h file being on include folder it givies me an error fatal error vec.h :no such file or directory.

**Comment by bimarsh123** [comment]
Not only vec.h but all the include header file gets no such file or directory error.

**Comment by avun1t** [comment]
Did you use the -Iinclude/ switch when compiling?

**Comment by bimarsh123** [comment]
where should I use it on the top of my code before include iostream?

**Comment by bimarsh123** [comment]
#include "Switch.h" this command itself is giving No such file or directory error/
