### ISSUE TITLE
Doesn't run under when compiled with Code::Blocks IDE

### ISSUE THREAD

**Issue by avun1t** [avun1t/Raytracer#3]

**Comment by bimarsh123** [comment]
For those of you who are trying to run on code blocks try visual studio. The output gets generated perfectly. Also if any one faces No such file or directory for .header file use #include "include/headerfile.h" instead of #include <headerfile.h> for all the header files

**Comment by avun1t** [comment]
> Also if any one faces No such file or directory for .header file use #include "include/headerfile.h" instead of #include <headerfile.h> for all the header files

This generally shouldn't be a problem if you use the `-Iinclude/` switch when compiling.

I'll try to compile with the mingw gcc on linux when I get home and see if it only affects Windows computers.
